project:
  name: flaresolverr-proj
  services:
    - hostname: flaresolverr
      type: docker@26.1.5
      minContainers: 1
      maxContainers: 1
      verticalAutoscaling:
        cpu: 1
        ram: 1
        disk: 5
        cpuMode: SHARED
        minFreeCpuCores: 1
        minFreeRamGB: 0.125
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - port: 8191
          protocol: http
